---
- name: Install Helm
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - gnupg

- name: Download Helm GPG key
  shell: "curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null"
  args:
    executable: /bin/bash

- name: Add Helm repository to sources.list
  shell: 'echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list'
  args:
    executable: /bin/bash

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Helm
  apt:
    name: helm
    state: present
