apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: docker-daemon-config
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: docker-daemon-config
  template:
    metadata:
      labels:
        name: docker-daemon-config
    spec:
      volumes:
      - name: docker-config
        configMap:
          name: docker-daemon-config
      containers:
      - name: docker-daemon-config
        image: alpine
        command: ["sh", "-c"]
        args:
        - cp /etc/docker/daemon.json /etc/docker/daemon.json.bak && \
          cp /etc/docker/daemon.json /etc/docker/daemon.json.orig && \
          cp /etc/docker/daemon.json /etc/docker/daemon.json.new && \
          jq -s '.[0] * .[1]' /etc/docker/daemon.json.orig /etc/docker/daemon.json.new > /etc/docker/daemon.json && \
          rm /etc/docker/daemon.json.orig /etc/docker/daemon.json.new && \
          docker restart docker
        volumeMounts:
        - name: docker-config
          mountPath: /etc/docker
        securityContext:
          privileged: true

# kubectl create configmap docker-daemon-config --from-file=docker-daemon-config.json -n kube-system
# kubectl apply -f daemonset.yaml
