apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask-app-deployment
  labels:
    app: my-flask-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-flask-app
  template:
    metadata:
      labels:
        app: my-flask-app
    spec:
      containers:
      - name: my-flask-app-container
        image: kareempythweb.duckdns.org/python-web-app-repo/my-website-image:latest  # Full image URL including Nexus repository
        resources:
          requests:
            memory: "1000Mi"  # Adjust these values as needed
          limits:
            memory: "2000Mi"
        ports:
        - containerPort: 3030
      imagePullSecrets:
      - name: nexus-credentials-secret  # Reference the Secret containing your Nexus credentials9

      # sudo docker pull DSN_SERVER-NAME:6000/python-web-app-repo/my-website-image