apiVersion: v1
kind: Service
metadata:
  name: my-flask-app-service
spec:
  selector:
    app: my-flask-app  # This selector should match the labels in your Deployment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3030  # The container port your Flask app is listening on
  type: LoadBalancer  # Use LoadBalancer if running on a cloud provider
