---
# - name: Move Jenkins Data Directory
#   hosts: your_ec2_instance
#   become: yes
#   become_user: jenkins  # Change this to the user that runs Jenkins if needed
#   tasks:
    - name: Stop Jenkins Service
      systemd:
        name: jenkins
        state: stopped
      become: yes

    - name: Create Destination Directory
      ansible.builtin.file:
        path: /new/directory/jenkins
        state: directory
      become: yes

    - name: Copy Jenkins Data to New Directory
      ansible.builtin.command: rsync -a /var/lib/jenkins/ /new/directory/jenkins/
      changed_when: false  # Avoid marking the task as changed when using rsync

    - name: Update Jenkins Configuration
      lineinfile:
        path: /etc/default/jenkins  # Change this path if needed
        line: 'JENKINS_HOME="/new/directory/jenkins"'
      become: yes

    - name: Start Jenkins Service
      systemd:
        name: jenkins
        state: started
      become: yes
