---
- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Create Nginx configuration file
  template:
    src: nginx-site.conf.j2
    dest: /etc/nginx/sites-available/pythonwebapp.duckdns.org
  notify:
    - Reload Nginx

- name: Create symbolic link to enable Nginx configuration
  become: yes
  file:
    src: /etc/nginx/sites-available/pythonwebapp.duckdns.org
    dest: /etc/nginx/sites-enabled/pythonwebapp.duckdns.org
    state: link
  notify:
    - Reload Nginx

- name: restart nginx service
  systemd:
    name: nginx
    state: restarted

- name: Stop nginx service
  systemd:
    name: nginx
    state: stopped

- name: Install Certbot and Python3-Certbot-Nginx
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - certbot
    - python3-certbot-nginx

- name: Obtain SSL certificate using Certbot
  command: sudo certbot certonly --standalone -d pythonwebapp.duckdns.org --register-unsafely-without-email --agree-tos --force-renewal
  ignore_errors: yes

- name: restart nginx service
  systemd:
    name: nginx
    state: restarted
