---
    - name: Remove Docker-related packages
      apt:
        name:
          - docker.io
          - docker-doc
          - docker-compose
          - podman-docker
          - containerd
          - runc
        state: absent
      become: yes

    - name: Update apt package index and install required packages
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present
      become: yes

    - name: Download Docker's official GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.gpg

    - name: Make the GPG key readable
      file:
        path: /etc/apt/keyrings/docker.gpg
        mode: 'a+r'
      become: yes

    - name: Add Docker's GPG key to trusted keys
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      become: yes

    - name: Set up Docker repository
      shell: |
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo $VERSION_CODENAME) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      become: yes

    - name: Update apt package index again
      apt:
        update_cache: yes
      become: yes

    - name: Install Docker Engine, containerd, and Docker Compose
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose
        state: present
      become: yes
