---
- name: Install Nexus on EC2 instance
  hosts: [nex_ec2_ip]
  become: true

  tasks:
     - name: Run Nexus Role
       include_role:
         name: nexus
         
     - name: Run nginx Role
       include_role:
         name: nginx